engines:
  duplication:
    enabled: true
    config:
      languages:
        python:

  fixme:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
exclude_paths:
  - examples/**
  - tests/**
  - docs/**
ratings:
  paths:
    - satella/**
